name: Main

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on:
      - ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - run: mvn test
